# - hosts: localhost
#   tasks:
#     - name: install something
#       yum:
#         name: hello
#         state: present
#       register: result
#
#     - debug: var=result
#
#     - name: remove something
#       yum:
#         name: hello
#         state: remove

- hosts: localhost
  connection: local
  tasks:
  - name: install something
    shell: "echo 'hello worl'"

  - name: test assert
    assert:
      that:
        - true

  - name: get list of changed files
    shell: "git diff --name-only {{ lookup('env', 'GIT_PREVIOUS_SUCCESSFUL_COMMIT') }}"
    register: git_diff

  - debug: var=git_diff
